version: '2.3'

services:
  db: 
    image: postgres:latest
    container_name: shopDB
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=yanasirina
      - POSTGRES_USER=yanasirina
      - POSTGRES_DB=dbforshop