CREATE TABLE brand
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_brand PRIMARY KEY (id)
);

CREATE TABLE buyer
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255),
    email VARCHAR(255),
    phone VARCHAR(255),
    CONSTRAINT pk_buyer PRIMARY KEY (id)
);

CREATE TABLE "order"
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sales_date TIMESTAMP WITHOUT TIME ZONE,
    status     SMALLINT,
    buyer_id   BIGINT,
    user_id    BIGINT,
    CONSTRAINT pk_order PRIMARY KEY (id)
);

CREATE TABLE order_item
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id        BIGINT,
    product_item_id BIGINT,
    quantity        INTEGER,
    CONSTRAINT pk_orderitem PRIMARY KEY (id)
);

CREATE TABLE product
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255),
    description    VARCHAR(255),
    price          FLOAT,
    brand_id       BIGINT,
    productitem_id BIGINT,
    CONSTRAINT pk_product PRIMARY KEY (id)
);

CREATE TABLE product_item
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255),
    quantity INTEGER,
    size_id  BIGINT,
    CONSTRAINT pk_productitem PRIMARY KEY (id)
);

CREATE TABLE role
(
    id   BIGINT NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_role PRIMARY KEY (id)
);

CREATE TABLE size
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_size PRIMARY KEY (id)
);

CREATE TABLE "user"
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255),
    password VARCHAR(255),
    CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE user_roles
(
    user_id  BIGINT NOT NULL,
    roles_id BIGINT NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (user_id, roles_id)
);

ALTER TABLE order_item
    ADD CONSTRAINT FK_ORDERITEM_ON_ORDER FOREIGN KEY (order_id) REFERENCES "order" (id);

ALTER TABLE order_item
    ADD CONSTRAINT FK_ORDERITEM_ON_PRODUCT_ITEM FOREIGN KEY (product_item_id) REFERENCES product_item (id);

ALTER TABLE "order"
    ADD CONSTRAINT FK_ORDER_ON_BUYER FOREIGN KEY (buyer_id) REFERENCES buyer (id);

ALTER TABLE "order"
    ADD CONSTRAINT FK_ORDER_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);

ALTER TABLE product_item
    ADD CONSTRAINT FK_PRODUCTITEM_ON_SIZE FOREIGN KEY (size_id) REFERENCES size (id);

ALTER TABLE product
    ADD CONSTRAINT FK_PRODUCT_ON_BRAND FOREIGN KEY (brand_id) REFERENCES brand (id);

ALTER TABLE product
    ADD CONSTRAINT FK_PRODUCT_ON_PRODUCTITEM FOREIGN KEY (productitem_id) REFERENCES product_item (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (roles_id) REFERENCES role (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_user FOREIGN KEY (user_id) REFERENCES "user" (id);