spring:
  application:
    name: KidsShop
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/dbforshop
    username: yanasirina
    password: yanasirina
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5433/dbforshop
    user: yanasirina
    password: yanasirina
    schemas: public
  jpa:
    show-sql: true
    properties:
      hibernate.hibernate.format_sql: true

server:
  port: 7070